quadrantChart
    title "Cartographie de dangerosité des parties prenantes de MobiTech"
    x-axis "Fiabilité cyber" --> "Élevée"
    y-axis "Exposition" --> "Élevée"
    quadrant-1 "Zone de danger"
    quadrant-2 "Zone de contrôle"
    quadrant-3 "Zone de veille"
    quadrant-4 "Zone sûre"
    F3: [0.3, 0.8]
    C1: [0.6, 0.3]
    P2: [0.7, 0.2]
    F1: [0.5, 0.5]
    P1: [0.4, 0.6]
    F2: [0.2, 0.7]
