name: Add Planning Key

on:
  push:
    branches:
      - master
      - main

jobs:
  add_planning_key:
    name: Add Planning Key to YAML Files
    # Assurez-vous que l'action a les permissions requises pour pousser des modifications
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # Cette option est importante pour les pushes
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyyaml

      - name: Add planning key to root.yaml files
        run: |
          # Exécuter le script
          python deployment/src/add-key-planning.py

          # Vérifier le contenu après modification
          echo "Contenu du fichier root.yaml après modification:"
          cat root.yaml | grep -A 10 planning || echo "La clé planning n'est pas présente"

      - name: Debug file changes
        run: |
          # Voir l'état des fichiers
          git status
          git diff root.yaml

      - name: Commit and push changes
        run: |
          # Configurer Git
          git config --global user.name 'dirtdover'
          git config --global user.email 'benjaminmbureau@gmail.com'

          # Forcer l'ajout du fichier modifié
          git add root.yaml

          # Vérifier s'il y a des modifications
          if git diff --staged --quiet; then
            echo "Aucune modification détectée dans root.yaml"
          else
            echo "Modifications détectées, création d'un commit"
            git commit -m "Add planning structure to root.yaml files"
            git push
          fi
